import * as all_themes from "react-syntax-highlighter/dist/esm/styles/hljs";

export const themes = [
  { name: "a11yDark", value: all_themes.a11yDark },
  { name: "a11yLight", value: all_themes.a11yLight },
  { name: "agate", value: all_themes.agate },
  { name: "anOldHope", value: all_themes.anOldHope },
  { name: "androidstudio", value: all_themes.androidstudio },
  { name: "arduinoLight", value: all_themes.arduinoLight },
  { name: "arta", value: all_themes.arta },
  { name: "ascetic", value: all_themes.ascetic },
  { name: "atelierCaveDark", value: all_themes.atelierCaveDark },
  { name: "atelierCaveLight", value: all_themes.atelierCaveLight },
  { name: "atelierDuneDark", value: all_themes.atelierDuneDark },
  { name: "atelierDuneLight", value: all_themes.atelierDuneLight },
  { name: "atelierEstuaryDark", value: all_themes.atelierEstuaryDark },
  { name: "atelierEstuaryLight", value: all_themes.atelierEstuaryLight },
  { name: "atelierForestDark", value: all_themes.atelierForestDark },
  { name: "atelierForestLight", value: all_themes.atelierForestLight },
  { name: "atelierHeathDark", value: all_themes.atelierHeathDark },
  { name: "atelierHeathLight", value: all_themes.atelierHeathLight },
  { name: "atelierLakesideDark", value: all_themes.atelierLakesideDark },
  { name: "atelierLakesideLight", value: all_themes.atelierLakesideLight },
  { name: "atelierPlateauDark", value: all_themes.atelierPlateauDark },
  { name: "atelierPlateauLight", value: all_themes.atelierPlateauLight },
  { name: "atelierSavannaDark", value: all_themes.atelierSavannaDark },
  { name: "atelierSavannaLight", value: all_themes.atelierSavannaLight },
  { name: "atelierSeasideDark", value: all_themes.atelierSeasideDark },
  { name: "atelierSeasideLight", value: all_themes.atelierSeasideLight },
  { name: "atelierSulphurpoolDark", value: all_themes.atelierSulphurpoolDark },
  {
    name: "atelierSulphurpoolLight",
    value: all_themes.atelierSulphurpoolLight,
  },
  { name: "atomOneDarkReasonable", value: all_themes.atomOneDarkReasonable },
  { name: "atomOneDark", value: all_themes.atomOneDark },
  { name: "atomOneLight", value: all_themes.atomOneLight },
  { name: "brownPaper", value: all_themes.brownPaper },
  { name: "codepenEmbed", value: all_themes.codepenEmbed },
  { name: "colorBrewer", value: all_themes.colorBrewer },
  { name: "darcula", value: all_themes.darcula },
  { name: "dark", value: all_themes.dark },
  { name: "defaultStyle", value: all_themes.defaultStyle },
  { name: "docco", value: all_themes.docco },
  { name: "dracula", value: all_themes.dracula },
  { name: "far", value: all_themes.far },
  { name: "foundation", value: all_themes.foundation },
  { name: "githubGist", value: all_themes.githubGist },
  { name: "github", value: all_themes.github },
  { name: "gml", value: all_themes.gml },
  { name: "googlecode", value: all_themes.googlecode },
  { name: "gradientDark", value: all_themes.gradientDark },
  { name: "grayscale", value: all_themes.grayscale },
  { name: "gruvboxDark", value: all_themes.gruvboxDark },
  { name: "gruvboxLight", value: all_themes.gruvboxLight },
  { name: "hopscotch", value: all_themes.hopscotch },
  { name: "hybrid", value: all_themes.hybrid },
  { name: "idea", value: all_themes.idea },
  { name: "irBlack", value: all_themes.irBlack },
  { name: "isblEditorDark", value: all_themes.isblEditorDark },
  { name: "isblEditorLight", value: all_themes.isblEditorLight },
  { name: "kimbieDark", value: all_themes.kimbieDark },
  { name: "kimbieLight", value: all_themes.kimbieLight },
  { name: "lightfair", value: all_themes.lightfair },
  { name: "lioshi", value: all_themes.lioshi },
  { name: "magula", value: all_themes.magula },
  { name: "monoBlue", value: all_themes.monoBlue },
  { name: "monokaiSublime", value: all_themes.monokaiSublime },
  { name: "monokai", value: all_themes.monokai },
  { name: "nightOwl", value: all_themes.nightOwl },
  { name: "nnfxDark", value: all_themes.nnfxDark },
  { name: "nnfx", value: all_themes.nnfx },
  { name: "nord", value: all_themes.nord },
  { name: "obsidian", value: all_themes.obsidian },
  { name: "ocean", value: all_themes.ocean },
  { name: "paraisoDark", value: all_themes.paraisoDark },
  { name: "paraisoLight", value: all_themes.paraisoLight },
  { name: "pojoaque", value: all_themes.pojoaque },
  { name: "purebasic", value: all_themes.purebasic },
  { name: "qtcreatorDark", value: all_themes.qtcreatorDark },
  { name: "qtcreatorLight", value: all_themes.qtcreatorLight },
  { name: "railscasts", value: all_themes.railscasts },
  { name: "rainbow", value: all_themes.rainbow },
  { name: "routeros", value: all_themes.routeros },
  { name: "schoolBook", value: all_themes.schoolBook },
  { name: "shadesOfPurple", value: all_themes.shadesOfPurple },
  { name: "solarizedDark", value: all_themes.solarizedDark },
  { name: "solarizedLight", value: all_themes.solarizedLight },
  { name: "srcery", value: all_themes.srcery },
  { name: "stackoverflowDark", value: all_themes.stackoverflowDark },
  { name: "stackoverflowLight", value: all_themes.stackoverflowLight },
  { name: "sunburst", value: all_themes.sunburst },
  { name: "tomorrowNightBlue", value: all_themes.tomorrowNightBlue },
  { name: "tomorrowNightBright", value: all_themes.tomorrowNightBright },
  { name: "tomorrowNightEighties", value: all_themes.tomorrowNightEighties },
  { name: "tomorrowNight", value: all_themes.tomorrowNight },
  { name: "tomorrow", value: all_themes.tomorrow },
  { name: "vs", value: all_themes.vs },
  { name: "vs2015", value: all_themes.vs2015 },
  { name: "xcode", value: all_themes.xcode },
  { name: "xt256", value: all_themes.xt256 },
  { name: "zenburn", value: all_themes.zenburn },
];

const all_themes_options = themes.map((ele) => {
  return {
    value: ele.name,
    label: ele.name,
  };
});

export default all_themes_options;
